# Extract PII from an LM

# dataset_args:
#   dataset_path: /h/dadsetan/analysing_pii_leakage/src/pii_leakage/extern/echr
#   dataset_mode: undefended
#   sample_duplication_rate: 1

attack_args:
  attack_name: naive_extraction
  sampling_rate: 100
  seq_len: 128

model_args:
  architecture: gpt2
  pre_trained: True
  model_ckpt: /h/dadsetan/fine_tune_dp8_run1 # Edit this path to try your own model.

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False
